#this file will be for testing api connections
# Wil need the following structure for Kalshi API:
# - Kalshi Access Key
# - Kalshi Access Timestamp
# - Kalshi Access Signature
# - The above signature is generated by signing a concatenation of the timestamp, the HTTP method and the path.